"""esquema inicial

Revision ID: 406210e8504a
Revises: 
Create Date: 2026-09-14 11:22:14.475767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406210e8504a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cedula_ruc', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cedula_ruc'), 'clientes', ['cedula_ruc'], unique=True)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas_por_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', 'VENCIDO', name='estado_cuenta_pagar'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('costo_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repuestos_codigo'), 'repuestos', ['codigo'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'MECANICO', 'CAJERO', 'CLIENTE', name='rol_usuario'), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=15), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('vin_chasis', sa.String(length=40), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('kilometraje_actual', sa.Integer(), nullable=True),
    sa.Column('foto_placa_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_table('caja_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('usuario_apertura_id', sa.Integer(), nullable=True),
    sa.Column('monto_apertura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usuario_cierre_id', sa.Integer(), nullable=True),
    sa.Column('monto_cierre_esperado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_cierre_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('cerrada', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_apertura_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_cierre_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('egresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('NOMINA', 'REPUESTOS', 'ALQUILER', 'SERVICIOS_BASICOS', 'HERRAMIENTAS', 'IMPUESTOS', 'MARKETING', 'MANTENIMIENTO_LOCAL', 'OTROS', name='categoria_egreso'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'OTRO', name='metodo_pago_egreso'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_registro_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_registro_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordenes_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kilometraje_ingreso', sa.Integer(), nullable=True),
    sa.Column('descripcion_problema', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'ENTREGADO', 'CANCELADO', name='estado_orden'), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'NORMAL', 'ALTA', 'URGENTE', name='prioridad_orden'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mecanico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADO', name='estado_comision'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mecanico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_id')
    )
    op.create_table('cuentas_por_cobrar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', 'VENCIDO', name='estado_cuenta_cobrar'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('MANO_OBRA', 'REPUESTO', name='tipo_detalle_orden'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('PLACA', 'ANTES', 'DESPUES', 'COMPROBANTE', name='tipo_foto'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'OTRO', name='metodo_pago'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_registro_id', sa.Integer(), nullable=True),
    sa.Column('comprobante_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['usuario_registro_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE', name='tipo_movimiento_inventario'), nullable=False),
    sa.Column('motivo', sa.Enum('COMPRA', 'USO_EN_ORDEN', 'AJUSTE_INVENTARIO', 'DEVOLUCION', name='motivo_movimiento_inventario'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_inventario')
    op.drop_table('ingresos')
    op.drop_table('fotos')
    op.drop_table('detalle_ordenes')
    op.drop_table('cuentas_por_cobrar')
    op.drop_table('comisiones')
    op.drop_table('ordenes_trabajo')
    op.drop_table('egresos')
    op.drop_table('caja_diaria')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_repuestos_codigo'), table_name='repuestos')
    op.drop_table('repuestos')
    op.drop_table('cuentas_por_pagar')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_clientes_cedula_ruc'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
