"""seguridad: auditoria, sesiones, terminos y consentimiento

Revision ID: 79d82987b130
Revises: ee9201d27f45
Create Date: 2026-10-04 17:22:47.107834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d82987b130'
down_revision: Union[str, None] = 'ee9201d27f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('entidad', sa.String(length=60), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('cambios', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_creado_en'), 'audit_logs', ['creado_en'], unique=False)
    op.create_index(op.f('ix_audit_logs_entidad'), 'audit_logs', ['entidad'], unique=False)
    op.create_index(op.f('ix_audit_logs_organizacion_id'), 'audit_logs', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_usuario_id'), 'audit_logs', ['usuario_id'], unique=False)
    op.add_column('clientes', sa.Column('acepta_comunicaciones', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('clientes', sa.Column('anonimizado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('sesion_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('usuarios', sa.Column('terminos_version', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('terminos_aceptados_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'terminos_aceptados_en')
    op.drop_column('usuarios', 'terminos_version')
    op.drop_column('usuarios', 'sesion_version')
    op.drop_column('clientes', 'anonimizado_en')
    op.drop_column('clientes', 'acepta_comunicaciones')
    op.drop_index(op.f('ix_audit_logs_usuario_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organizacion_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entidad'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_creado_en'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
