"""saas_multi_tenant_inspeccion_timeline

Revision ID: ee9201d27f45
Revises: 406210e8504a
Create Date: 2026-09-17 12:38:49.795978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee9201d27f45'
down_revision: Union[str, None] = '406210e8504a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('ruc_identificacion', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizaciones_slug'), 'organizaciones', ['slug'], unique=True)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('es_matriz', sa.Boolean(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_organizacion_id'), 'sucursales', ['organizacion_id'], unique=False)
    # Solo al migrar una instalación anterior (de un único taller) hace falta
    # una organización a la que asignar los datos existentes. En una base
    # nueva no se crea nada: los talleres se dan de alta con crear_taller.py.
    op.execute(
        """
        INSERT INTO organizaciones (id, nombre, slug, plan, activo, creado_en, actualizado_en)
        SELECT 1, 'Taller Mecánico Central', 'taller-central', 'PRO', true, now(), now()
        WHERE EXISTS (SELECT 1 FROM usuarios)
        ON CONFLICT (id) DO NOTHING;

        INSERT INTO sucursales (id, organizacion_id, nombre, codigo, es_matriz, activa, creado_en, actualizado_en)
        SELECT 1, 1, 'Sede Matriz Norte', 'MAT-01', true, true, now(), now()
        WHERE EXISTS (SELECT 1 FROM organizaciones WHERE id = 1)
        ON CONFLICT (id) DO NOTHING;
        """
    )
    op.create_table('bahias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'OCUPADA', 'MANTENIMIENTO', 'RESERVADA', name='estado_bahia'), nullable=False),
    sa.Column('vehiculo_actual_id', sa.Integer(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_actual_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bahias_organizacion_id'), 'bahias', ['organizacion_id'], unique=False)
    op.create_table('documentos_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('MATRICULA', 'SEGURO', 'MANUAL', 'PERITAJE', 'FACTURA', 'OTRO', name='tipo_documento_vehiculo'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_vehiculo_vehiculo_id'), 'documentos_vehiculo', ['vehiculo_id'], unique=False)
    op.create_table('checklists_recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('nivel_combustible', sa.Integer(), nullable=False),
    sa.Column('radio', sa.Boolean(), nullable=False),
    sa.Column('herramientas', sa.Boolean(), nullable=False),
    sa.Column('gato_palanca', sa.Boolean(), nullable=False),
    sa.Column('llanta_emergencia', sa.Boolean(), nullable=False),
    sa.Column('antena', sa.Boolean(), nullable=False),
    sa.Column('documentos_vehiculo', sa.Boolean(), nullable=False),
    sa.Column('danos_graficos_json', sa.Text(), nullable=True),
    sa.Column('observaciones_recepcion', sa.Text(), nullable=True),
    sa.Column('firma_cliente_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_id')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('bahia_id', sa.Integer(), nullable=True),
    sa.Column('mecanico_asignado_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADA', 'CONFIRMADA', 'COMPLETADA', 'CANCELADA', 'NO_ASISTIO', name='estado_cita'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('organizacion_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bahia_id'], ['bahias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['mecanico_asignado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizaciones.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_cliente_id'), 'citas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_citas_organizacion_id'), 'citas', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_citas_vehiculo_id'), 'citas', ['vehiculo_id'], unique=False)
    op.create_table('fotos_vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('PLACA', 'FRENTE', 'PARTE_TRASERA', 'LATERAL_IZQUIERDO', 'LATERAL_DERECHO', 'INTERIOR', 'MOTOR', 'DANIO', 'ANTES', 'DESPUES', 'COMPROBANTE', name='tipo_foto_vehiculo'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fotos_vehiculo_vehiculo_id'), 'fotos_vehiculo', ['vehiculo_id'], unique=False)
    op.create_table('inspecciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspecciones_orden_id'), 'inspecciones', ['orden_id'], unique=False)
    op.create_table('detalle_inspecciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspeccion_id', sa.Integer(), nullable=False),
    sa.Column('sistema', sa.String(length=60), nullable=False),
    sa.Column('estado', sa.Enum('BUENO', 'REVISAR', 'DEFICIENTE', 'REQUIERE_REPARACION', name='estado_inspeccion_item'), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspeccion_id'], ['inspecciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_inspecciones_inspeccion_id'), 'detalle_inspecciones', ['inspeccion_id'], unique=False)
    op.add_column('caja_diaria', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.add_column('caja_diaria', sa.Column('organizacion_id', sa.Integer(), nullable=False))
    op.drop_constraint('caja_diaria_fecha_key', 'caja_diaria', type_='unique')
    op.create_index(op.f('ix_caja_diaria_fecha'), 'caja_diaria', ['fecha'], unique=False)
    op.create_index(op.f('ix_caja_diaria_organizacion_id'), 'caja_diaria', ['organizacion_id'], unique=False)
    op.create_foreign_key(None, 'caja_diaria', 'organizaciones', ['organizacion_id'], ['id'])
    op.create_foreign_key(None, 'caja_diaria', 'sucursales', ['sucursal_id'], ['id'])
    op.add_column('clientes', sa.Column('apellidos', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('whatsapp', sa.String(length=30), nullable=True))
    op.add_column('clientes', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('clientes', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('clientes', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('clientes', 'cedula_ruc',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_index('ix_clientes_cedula_ruc', table_name='clientes')
    op.create_index(op.f('ix_clientes_cedula_ruc'), 'clientes', ['cedula_ruc'], unique=False)
    op.create_index(op.f('ix_clientes_organizacion_id'), 'clientes', ['organizacion_id'], unique=False)
    op.create_foreign_key(None, 'clientes', 'organizaciones', ['organizacion_id'], ['id'])
    op.add_column('cuentas_por_cobrar', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_cuentas_por_cobrar_cliente_id'), 'cuentas_por_cobrar', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cuentas_por_cobrar_orden_id'), 'cuentas_por_cobrar', ['orden_id'], unique=False)
    op.create_index(op.f('ix_cuentas_por_cobrar_organizacion_id'), 'cuentas_por_cobrar', ['organizacion_id'], unique=False)
    op.create_foreign_key(None, 'cuentas_por_cobrar', 'organizaciones', ['organizacion_id'], ['id'])
    op.add_column('cuentas_por_pagar', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_cuentas_por_pagar_organizacion_id'), 'cuentas_por_pagar', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_cuentas_por_pagar_proveedor_id'), 'cuentas_por_pagar', ['proveedor_id'], unique=False)
    op.create_foreign_key(None, 'cuentas_por_pagar', 'organizaciones', ['organizacion_id'], ['id'])
    op.add_column('detalle_ordenes', sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.create_index(op.f('ix_detalle_ordenes_orden_id'), 'detalle_ordenes', ['orden_id'], unique=False)
    op.add_column('egresos', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.add_column('egresos', sa.Column('numero_comprobante', sa.String(length=100), nullable=True))
    op.add_column('egresos', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_egresos_organizacion_id'), 'egresos', ['organizacion_id'], unique=False)
    op.create_foreign_key(None, 'egresos', 'organizaciones', ['organizacion_id'], ['id'])
    op.create_foreign_key(None, 'egresos', 'sucursales', ['sucursal_id'], ['id'])
    op.add_column('fotos', sa.Column('descripcion', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_fotos_orden_id'), 'fotos', ['orden_id'], unique=False)
    op.add_column('ingresos', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.add_column('ingresos', sa.Column('numero_referencia', sa.String(length=100), nullable=True))
    op.add_column('ingresos', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_ingresos_cliente_id'), 'ingresos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ingresos_orden_id'), 'ingresos', ['orden_id'], unique=False)
    op.create_index(op.f('ix_ingresos_organizacion_id'), 'ingresos', ['organizacion_id'], unique=False)
    op.create_foreign_key(None, 'ingresos', 'sucursales', ['sucursal_id'], ['id'])
    op.create_foreign_key(None, 'ingresos', 'organizaciones', ['organizacion_id'], ['id'])
    op.add_column('movimientos_inventario', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.add_column('movimientos_inventario', sa.Column('stock_anterior', sa.Integer(), nullable=True))
    op.add_column('movimientos_inventario', sa.Column('stock_nuevo', sa.Integer(), nullable=True))
    op.add_column('movimientos_inventario', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('movimientos_inventario', sa.Column('observacion', sa.String(length=255), nullable=True))
    op.add_column('movimientos_inventario', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_movimientos_inventario_orden_id'), 'movimientos_inventario', ['orden_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_organizacion_id'), 'movimientos_inventario', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_repuesto_id'), 'movimientos_inventario', ['repuesto_id'], unique=False)
    op.create_foreign_key(None, 'movimientos_inventario', 'sucursales', ['sucursal_id'], ['id'])
    op.create_foreign_key(None, 'movimientos_inventario', 'organizaciones', ['organizacion_id'], ['id'])
    op.create_foreign_key(None, 'movimientos_inventario', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('ordenes_trabajo', sa.Column('numero_orden', sa.String(length=30), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('fecha_entrega_estimada', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('fecha_entrega_real', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('motivo_ingreso', sa.Text(), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('trabajos_solicitados', sa.Text(), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('trabajos_realizados', sa.Text(), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('observaciones', sa.Text(), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('descuento', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('impuestos', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('total', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('firma_cliente_url', sa.String(length=500), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('firma_mecanico_url', sa.String(length=500), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_ordenes_trabajo_cliente_id'), 'ordenes_trabajo', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ordenes_trabajo_mecanico_id'), 'ordenes_trabajo', ['mecanico_id'], unique=False)
    op.create_index(op.f('ix_ordenes_trabajo_numero_orden'), 'ordenes_trabajo', ['numero_orden'], unique=False)
    op.create_index(op.f('ix_ordenes_trabajo_organizacion_id'), 'ordenes_trabajo', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_ordenes_trabajo_sucursal_id'), 'ordenes_trabajo', ['sucursal_id'], unique=False)
    op.create_index(op.f('ix_ordenes_trabajo_vehiculo_id'), 'ordenes_trabajo', ['vehiculo_id'], unique=False)
    op.create_foreign_key(None, 'ordenes_trabajo', 'organizaciones', ['organizacion_id'], ['id'])
    op.create_foreign_key(None, 'ordenes_trabajo', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'ordenes_trabajo', 'sucursales', ['sucursal_id'], ['id'])
    op.drop_column('ordenes_trabajo', 'fecha_entrega')
    op.drop_column('ordenes_trabajo', 'descripcion_problema')
    op.add_column('proveedores', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('proveedores', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('proveedores', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('proveedores', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('proveedores', 'ruc',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_index(op.f('ix_proveedores_organizacion_id'), 'proveedores', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_proveedores_ruc'), 'proveedores', ['ruc'], unique=False)
    op.create_foreign_key(None, 'proveedores', 'organizaciones', ['organizacion_id'], ['id'])
    op.add_column('repuestos', sa.Column('sku', sa.String(length=60), nullable=True))
    op.add_column('repuestos', sa.Column('barcode', sa.String(length=60), nullable=True))
    op.add_column('repuestos', sa.Column('marca', sa.String(length=80), nullable=True))
    op.add_column('repuestos', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('repuestos', sa.Column('ubicacion', sa.String(length=80), nullable=True))
    op.add_column('repuestos', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.drop_index('ix_repuestos_codigo', table_name='repuestos')
    op.create_index(op.f('ix_repuestos_codigo'), 'repuestos', ['codigo'], unique=False)
    op.create_index(op.f('ix_repuestos_barcode'), 'repuestos', ['barcode'], unique=False)
    op.create_index(op.f('ix_repuestos_organizacion_id'), 'repuestos', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_repuestos_sku'), 'repuestos', ['sku'], unique=False)
    op.create_foreign_key(None, 'repuestos', 'organizaciones', ['organizacion_id'], ['id'])
    op.add_column('usuarios', sa.Column('organizacion_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('cargo', sa.String(length=80), nullable=True))
    op.add_column('usuarios', sa.Column('especialidad', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_usuarios_organizacion_id'), 'usuarios', ['organizacion_id'], unique=False)
    op.create_foreign_key(None, 'usuarios', 'organizaciones', ['organizacion_id'], ['id'])
    op.create_foreign_key(None, 'usuarios', 'sucursales', ['sucursal_id'], ['id'])
    op.add_column('vehiculos', sa.Column('combustible', sa.String(length=30), nullable=True))
    op.add_column('vehiculos', sa.Column('cilindraje', sa.String(length=30), nullable=True))
    op.add_column('vehiculos', sa.Column('transmision', sa.String(length=30), nullable=True))
    op.add_column('vehiculos', sa.Column('kilometraje_anterior', sa.Integer(), nullable=True))
    op.add_column('vehiculos', sa.Column('proximo_mantenimiento_km', sa.Integer(), nullable=True))
    op.add_column('vehiculos', sa.Column('estado', sa.String(length=30), server_default='activo', nullable=False))
    op.add_column('vehiculos', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('vehiculos', sa.Column('organizacion_id', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('vehiculos', 'placa',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('vehiculos', 'vin_chasis',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('vehiculos', 'tipo',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.drop_index('ix_vehiculos_placa', table_name='vehiculos')
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=False)
    op.create_index(op.f('ix_vehiculos_cliente_id'), 'vehiculos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vehiculos_organizacion_id'), 'vehiculos', ['organizacion_id'], unique=False)
    op.create_index(op.f('ix_vehiculos_vin_chasis'), 'vehiculos', ['vin_chasis'], unique=False)
    op.create_foreign_key(None, 'vehiculos', 'organizaciones', ['organizacion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehiculos', type_='foreignkey')
    op.drop_index(op.f('ix_vehiculos_vin_chasis'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_organizacion_id'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_cliente_id'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.create_index('ix_vehiculos_placa', 'vehiculos', ['placa'], unique=True)
    op.alter_column('vehiculos', 'tipo',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('vehiculos', 'vin_chasis',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('vehiculos', 'placa',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_column('vehiculos', 'organizacion_id')
    op.drop_column('vehiculos', 'notas')
    op.drop_column('vehiculos', 'estado')
    op.drop_column('vehiculos', 'proximo_mantenimiento_km')
    op.drop_column('vehiculos', 'kilometraje_anterior')
    op.drop_column('vehiculos', 'transmision')
    op.drop_column('vehiculos', 'cilindraje')
    op.drop_column('vehiculos', 'combustible')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_organizacion_id'), table_name='usuarios')
    op.drop_column('usuarios', 'especialidad')
    op.drop_column('usuarios', 'cargo')
    op.drop_column('usuarios', 'sucursal_id')
    op.drop_column('usuarios', 'organizacion_id')
    op.drop_constraint(None, 'repuestos', type_='foreignkey')
    op.drop_index(op.f('ix_repuestos_sku'), table_name='repuestos')
    op.drop_index(op.f('ix_repuestos_organizacion_id'), table_name='repuestos')
    op.drop_index(op.f('ix_repuestos_barcode'), table_name='repuestos')
    op.drop_index(op.f('ix_repuestos_codigo'), table_name='repuestos')
    op.create_index('ix_repuestos_codigo', 'repuestos', ['codigo'], unique=True)
    op.drop_column('repuestos', 'organizacion_id')
    op.drop_column('repuestos', 'ubicacion')
    op.drop_column('repuestos', 'descripcion')
    op.drop_column('repuestos', 'marca')
    op.drop_column('repuestos', 'barcode')
    op.drop_column('repuestos', 'sku')
    op.drop_constraint(None, 'proveedores', type_='foreignkey')
    op.drop_index(op.f('ix_proveedores_ruc'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_organizacion_id'), table_name='proveedores')
    op.alter_column('proveedores', 'ruc',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('proveedores', 'organizacion_id')
    op.drop_column('proveedores', 'notas')
    op.drop_column('proveedores', 'direccion')
    op.drop_column('proveedores', 'email')
    op.add_column('ordenes_trabajo', sa.Column('descripcion_problema', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('fecha_entrega', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ordenes_trabajo', type_='foreignkey')
    op.drop_constraint(None, 'ordenes_trabajo', type_='foreignkey')
    op.drop_constraint(None, 'ordenes_trabajo', type_='foreignkey')
    op.drop_index(op.f('ix_ordenes_trabajo_vehiculo_id'), table_name='ordenes_trabajo')
    op.drop_index(op.f('ix_ordenes_trabajo_sucursal_id'), table_name='ordenes_trabajo')
    op.drop_index(op.f('ix_ordenes_trabajo_organizacion_id'), table_name='ordenes_trabajo')
    op.drop_index(op.f('ix_ordenes_trabajo_numero_orden'), table_name='ordenes_trabajo')
    op.drop_index(op.f('ix_ordenes_trabajo_mecanico_id'), table_name='ordenes_trabajo')
    op.drop_index(op.f('ix_ordenes_trabajo_cliente_id'), table_name='ordenes_trabajo')
    op.drop_column('ordenes_trabajo', 'organizacion_id')
    op.drop_column('ordenes_trabajo', 'firma_mecanico_url')
    op.drop_column('ordenes_trabajo', 'firma_cliente_url')
    op.drop_column('ordenes_trabajo', 'monto_pagado')
    op.drop_column('ordenes_trabajo', 'total')
    op.drop_column('ordenes_trabajo', 'impuestos')
    op.drop_column('ordenes_trabajo', 'descuento')
    op.drop_column('ordenes_trabajo', 'subtotal')
    op.drop_column('ordenes_trabajo', 'observaciones')
    op.drop_column('ordenes_trabajo', 'trabajos_realizados')
    op.drop_column('ordenes_trabajo', 'trabajos_solicitados')
    op.drop_column('ordenes_trabajo', 'motivo_ingreso')
    op.drop_column('ordenes_trabajo', 'fecha_entrega_real')
    op.drop_column('ordenes_trabajo', 'fecha_entrega_estimada')
    op.drop_column('ordenes_trabajo', 'cliente_id')
    op.drop_column('ordenes_trabajo', 'sucursal_id')
    op.drop_column('ordenes_trabajo', 'numero_orden')
    op.drop_constraint(None, 'movimientos_inventario', type_='foreignkey')
    op.drop_constraint(None, 'movimientos_inventario', type_='foreignkey')
    op.drop_constraint(None, 'movimientos_inventario', type_='foreignkey')
    op.drop_index(op.f('ix_movimientos_inventario_repuesto_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_organizacion_id'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_orden_id'), table_name='movimientos_inventario')
    op.drop_column('movimientos_inventario', 'organizacion_id')
    op.drop_column('movimientos_inventario', 'observacion')
    op.drop_column('movimientos_inventario', 'usuario_id')
    op.drop_column('movimientos_inventario', 'stock_nuevo')
    op.drop_column('movimientos_inventario', 'stock_anterior')
    op.drop_column('movimientos_inventario', 'sucursal_id')
    op.drop_constraint(None, 'ingresos', type_='foreignkey')
    op.drop_constraint(None, 'ingresos', type_='foreignkey')
    op.drop_index(op.f('ix_ingresos_organizacion_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_orden_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_cliente_id'), table_name='ingresos')
    op.drop_column('ingresos', 'organizacion_id')
    op.drop_column('ingresos', 'numero_referencia')
    op.drop_column('ingresos', 'sucursal_id')
    op.drop_index(op.f('ix_fotos_orden_id'), table_name='fotos')
    op.drop_column('fotos', 'descripcion')
    op.drop_constraint(None, 'egresos', type_='foreignkey')
    op.drop_constraint(None, 'egresos', type_='foreignkey')
    op.drop_index(op.f('ix_egresos_organizacion_id'), table_name='egresos')
    op.drop_column('egresos', 'organizacion_id')
    op.drop_column('egresos', 'numero_comprobante')
    op.drop_column('egresos', 'sucursal_id')
    op.drop_index(op.f('ix_detalle_ordenes_orden_id'), table_name='detalle_ordenes')
    op.drop_column('detalle_ordenes', 'costo_unitario')
    op.drop_constraint(None, 'cuentas_por_pagar', type_='foreignkey')
    op.drop_index(op.f('ix_cuentas_por_pagar_proveedor_id'), table_name='cuentas_por_pagar')
    op.drop_index(op.f('ix_cuentas_por_pagar_organizacion_id'), table_name='cuentas_por_pagar')
    op.drop_column('cuentas_por_pagar', 'organizacion_id')
    op.drop_constraint(None, 'cuentas_por_cobrar', type_='foreignkey')
    op.drop_index(op.f('ix_cuentas_por_cobrar_organizacion_id'), table_name='cuentas_por_cobrar')
    op.drop_index(op.f('ix_cuentas_por_cobrar_orden_id'), table_name='cuentas_por_cobrar')
    op.drop_index(op.f('ix_cuentas_por_cobrar_cliente_id'), table_name='cuentas_por_cobrar')
    op.drop_column('cuentas_por_cobrar', 'organizacion_id')
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_index(op.f('ix_clientes_organizacion_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cedula_ruc'), table_name='clientes')
    op.create_index('ix_clientes_cedula_ruc', 'clientes', ['cedula_ruc'], unique=True)
    op.alter_column('clientes', 'cedula_ruc',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('clientes', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('clientes', 'organizacion_id')
    op.drop_column('clientes', 'notas')
    op.drop_column('clientes', 'ciudad')
    op.drop_column('clientes', 'whatsapp')
    op.drop_column('clientes', 'apellidos')
    op.drop_constraint(None, 'caja_diaria', type_='foreignkey')
    op.drop_constraint(None, 'caja_diaria', type_='foreignkey')
    op.drop_index(op.f('ix_caja_diaria_organizacion_id'), table_name='caja_diaria')
    op.drop_index(op.f('ix_caja_diaria_fecha'), table_name='caja_diaria')
    op.create_unique_constraint('caja_diaria_fecha_key', 'caja_diaria', ['fecha'])
    op.drop_column('caja_diaria', 'organizacion_id')
    op.drop_column('caja_diaria', 'sucursal_id')
    op.drop_index(op.f('ix_detalle_inspecciones_inspeccion_id'), table_name='detalle_inspecciones')
    op.drop_table('detalle_inspecciones')
    op.drop_index(op.f('ix_inspecciones_orden_id'), table_name='inspecciones')
    op.drop_table('inspecciones')
    op.drop_index(op.f('ix_fotos_vehiculo_vehiculo_id'), table_name='fotos_vehiculo')
    op.drop_table('fotos_vehiculo')
    op.drop_index(op.f('ix_citas_vehiculo_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_organizacion_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_cliente_id'), table_name='citas')
    op.drop_table('citas')
    op.drop_table('checklists_recepcion')
    op.drop_index(op.f('ix_documentos_vehiculo_vehiculo_id'), table_name='documentos_vehiculo')
    op.drop_table('documentos_vehiculo')
    op.drop_index(op.f('ix_bahias_organizacion_id'), table_name='bahias')
    op.drop_table('bahias')
    op.drop_index(op.f('ix_sucursales_organizacion_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_organizaciones_slug'), table_name='organizaciones')
    op.drop_table('organizaciones')
    # ### end Alembic commands ###
